### ISSUE TITLE
APK file not found

### ISSUE THREAD

**Issue by evgeniisage** [microsoft/google-play-vsts-extension#170]
Hi,

When Using the Google Play task "Google Play Release" I get the following error message: 
Error: Not found apkFile: /Users/runner/runners/2.165.2/work/r1/a/xMobile/APK/DpwEmployee.apk
even despite the App Sign task completing successfully and leaving the apk in this directory.

I have added shell exec job both after "Sign APK" and before "Release" tasks with the following code:
**ls $(System.DefaultWorkingDirectory)/xMobile/APK**

After APK signing it gives the following output:
2020-04-16T20:58:13.6771090Z ##[section]Starting: shellexec 
2020-04-16T20:58:13.7035940Z ================================================================
2020-04-16T20:58:13.7037070Z Task         : Shell Exec
2020-04-16T20:58:13.7037930Z Description  : Execute shell commands without creating a shell file
2020-04-16T20:58:13.7038260Z Version      : 0.2.0
2020-04-16T20:58:13.7038950Z Author       : Tsuyoshi Ushio
2020-04-16T20:58:13.7040080Z Help         : Replace with markdown to show in help
2020-04-16T20:58:13.7040540Z ================================================================
2020-04-16T20:58:14.6298430Z [command]/bin/bash ./.tempexecution.sh
2020-04-16T20:58:14.6440140Z (node:806) Warning: Use Cipheriv for counter mode of aes-256-ctr
2020-04-16T20:58:14.6532280Z DpwEmployee.apk
2020-04-16T20:58:14.6533570Z keepme.txt
2020-04-16T20:58:14.6733090Z ##[section]Finishing: shellexec

But running the same code before releasing is giving an error message that file or folder does not exist. If I just leave 
**ls $(System.DefaultWorkingDirectory)** 

it shows nothing:

2020-04-16T20:58:28.7494410Z ##[section]Starting: shellexec 
2020-04-16T20:58:28.7714220Z ================================================================
2020-04-16T20:58:28.7715730Z Task         : Shell Exec
2020-04-16T20:58:28.7716580Z Description  : Execute shell commands without creating a shell file
2020-04-16T20:58:28.7716930Z Version      : 0.2.0
2020-04-16T20:58:28.7717650Z Author       : Tsuyoshi Ushio
2020-04-16T20:58:28.7718830Z Help         : Replace with markdown to show in help
2020-04-16T20:58:28.7719220Z ================================================================
2020-04-16T20:58:30.1502660Z (node:607) Warning: Use Cipheriv for counter mode of aes-256-ctr
2020-04-16T20:58:30.1520240Z [command]/bin/bash ./.tempexecution.sh
2020-04-16T20:58:30.1563840Z ##[section]Finishing: shellexec

Do you know what the issue may be with the extension not detecting APK? 

Please let me know should any additional information be required.

Thanks!

**Comment by evgeniisage** [comment]
Hi @leantk , @erjohnms , @lkillgore, can someone please take a look into this issue? It's almost been a week. If the provided info is not sufficient, will be happy to elaborate. Thanks!

**Comment by leantk** [comment]
@evgeniisage I've added it to the backlog and will try to get to it soon

**Comment by alexander-smolyakov** [comment]
Hello, @evgeniisage!

Thanks for your patience. 

After investigation, I can't say sure what this issue about without more information. Could you please run the pipeline again with the debug option set on and send logs? Also, it would be great if you are able to provide the YAML file for your pipeline.

**Comment by evgeniisage** [comment]
Hi @alexander-smolyakov, please find the logs attached here: 
[ReleaseLogs_Sage.zip](https://github.com/microsoft/google-play-vsts-extension/files/4590315/ReleaseLogs_Sage.zip)

And Yaml pipeline here: 
[YAML.zip](https://github.com/microsoft/google-play-vsts-extension/files/4590318/YAML.zip)

Thanks!

**Comment by alexander-smolyakov** [comment]
@evgeniisage, thank you for providing logs and YAML files!

As I can see from logs and YAML files you launch "Android signing" and "Google Play - Release" tasks in different pipelines. Because of this, they executed on different agents, you can see it at logs and that's why the "Google Play - Release" task can't find apk file (since signed apk file was stored on the different agent). So these tasks are designed to be used in one pipeline.

The "Android signing" task was executed on `2020-05-07T02: 05: 19.8695280Z Agent machine name: 'Mac-1579`. When the "Google Play - Release" task was executed on `2020-05-07T02: 07: 53.2809930Z Agent machine name: 'Mac-1477'`.

Could you please try to put "Android signing" and "Google Play - Release" tasks in one YAML file and run the pipeline again? This will guarantee that both tasks will be executed in the same pipeline and on the same agent.

I assume the working YAML file for you should look like this:  

```
variables:
  FileName: 'DpwEmployee'

steps:
- task: AndroidSigning@3
  displayName: 'Sign APK'
  inputs:
    apkFiles: '$(System.DefaultWorkingDirectory)/xMobile/APK/$(FileName).apk'
    apksignerKeystoreFile: Playupload.keystore
    apksignerKeystorePassword: '$(KeyPassword)'
    apksignerKeystoreAlias: 'upload_prod'
    apksignerKeyPassword: '$(KeyPassword)'

- task: ms-vsclient.google-play.google-play-release.GooglePlayRelease@3
  displayName: 'Release $(FileName).apk to alpha'
  inputs:
    serviceConnection: 'Google_Evgenii'
    apkFile: '$(System.DefaultWorkingDirectory)/xMobile/APK/$(FileName).apk'
```
