### ISSUE TITLE
Feature ask: Support optional 'prefix' for track

### ISSUE THREAD

**Issue by oproulx** [microsoft/google-play-vsts-extension#415]
Track is currently set to a dropdown with fixed options.  It would be nice to have the ability to target different form factors (automotive or wear).

API details:
The track name for a given form factor track can be computed as: "[prefix]:defaultTrackName". For example Wear OS form factor will have tracks with name: "wear:production", "wear:beta" and "wear:qa".

https://developers.google.com/android-publisher/tracks

Workaround for now is to hard code the string including the pre-fix in the track input.

**Comment by ismayilov-ismayil** [comment]
Hi @oproulx.  Thanks for reporting! We are working on more prioritized issues at the moment but will get back to this one soon.

**Comment by oproulx** [comment]
Thanks for the quick response!  The workaround works for now and if anyone searches the repo for 'wear' or 'automotive' the instructions should come up.

**Comment by mav10** [comment]
Well, I don't understand what instructions @oproulx is talking about.
Is it described in the google documentation? Then it looks like the current extension doesn't support it.

When I provide track: 'wear:qa' - I get an error
`
##[error]Error: Failed to update track wear:qa information. Failed with message: GaxiosError: Track not found: wear:qa.
`
Am I doing something wrong?
My example of task in Azure Pipeline

```
  - task: GooglePlayRelease@4
    inputs:
      serviceConnection: 'Google Play'
      applicationId: $(PRODUCT_BUNDLE_IDENTIFIER)
      action: 'SingleBundle'
      bundleFile: $(PROJECT_NAME)_${{ parameters.module }}_${{ parameters.region }}_$(VERSION_NAME).aab
      ${{ if eq(parameters.module, 'app') }}:
         track: 'internal'
      ${{ else }}:
         track: 'wear:qa'
      languageCode: 'en-EN'
      releaseName: $(VERSION_NAME)

```
