### ISSUE TITLE
Error "Only releases with status draft may be created on draft app." when no releases are in draft

### ISSUE THREAD

**Issue by beeradmoore** [microsoft/google-play-vsts-extension#470]
I am moving my CI/CD to Azure DevOps, and part of that is moving builds to Azure Pipeline.

My test Android app builds fine but while attempting to distribute to the store I get the error,

> Only releases with status draft may be created on draft app.

But the problem is there is only 1 track being used, the internal track, and there is not a build in draft.

<img width="955" alt="Image" src="https://github.com/user-attachments/assets/eb8bbc9f-322a-488c-a962-d3829d805b76" />

This is part of my current `azure-pipelines.yml`

```
    - task: GooglePlayRelease@4
      inputs:
        serviceEndpoint: 'GooglePlayConnection'
        track: 'internal'
        applicationId: '$(expectedBundleName)'
        action: 'SingleBundle'
        bundleFile: '$(platformSpecificOutputDirectory)/$(expectedBundleName).aab'
        releaseName: $(Build.BuildID)
        isDraftRelease: false
        changeLogFile: 'defaultReleaseNotes.txt'
```

If I change `isDraftRelease` to `true` it will upload but keep it in a draft state.

If I try follow up by immediately making the draft a completed app with 

```
    - task: GooglePlayStatusUpdate@2
      inputs:
        serviceEndpoint: 'GooglePlayConnection'
        track: 'internal'
        packageName: '$(expectedBundleName)'
        status: 'completed'
```

but then that will fail with the same error
